import os
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, BitsAndBytesConfig, DataCollatorForLanguageModeling
from trl import SFTTrainer
try:
    from trl import DataCollatorForCompletionOnlyLM
    HAS_COMP_COLLATOR = True
except ImportError:
    HAS_COMP_COLLATOR = False
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from src.utils.logger import get_logger

logger = get_logger(__name__)

class IndicSFTTrainer:
    """
    Phase 4: Supervised Fine-Tuning (SFT).
    This phase costs $0.00 in API credits since it trains entirely on your local/free cloud GPU.
    It maps the ultra-high-IQ JSON data generated by Groq directly onto your Qwen CPT model,
    teaching it to stop generating random text and start acting like a genius coding/reasoning assistant.
    """
    def __init__(self, cpt_model_dir: str, jsonl_dataset_path: str, output_dir: str):
        self.cpt_model_dir = cpt_model_dir
        self.jsonl_dataset_path = jsonl_dataset_path
        self.output_dir = output_dir

    def train(self):
        logger.info(f"Loading distilled reasoning dataset from {self.jsonl_dataset_path}")
        # The JSONL from the Groq script seamlessly integrates into this free dataloader
        dataset = load_dataset("json", data_files=self.jsonl_dataset_path)["train"]

        logger.info("Configuring 4-bit Quantization to maintain ultra-low cost hardware efficiency...")
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16 # Aligned with TrainingArguments
        )

        logger.info(f"Loading structurally fluent CPT Model from: {self.cpt_model_dir}")
        model = AutoModelForCausalLM.from_pretrained(
            self.cpt_model_dir,
            quantization_config=bnb_config,
            device_map="auto"
        )
        
        tokenizer = AutoTokenizer.from_pretrained(self.cpt_model_dir)
        tokenizer.pad_token = tokenizer.eos_token # Padding is essential for SFT batching loops
        
        model = prepare_model_for_kbit_training(model)

        logger.info("Injecting LoRA Matrix Adapters for Behavioral Tuning...")
        lora_config = LoraConfig(
            r=32,               # Rank is lower than CPT because we are only teaching it "behavior", not base language
            lora_alpha=64,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
            lora_dropout=0.05,
            bias="none",
            task_type="CAUSAL_LM"
            # NOTE: We NO LONGER need to unfreeze 'embed_tokens' here! 
            # Phase 2 (CPT) already taught the matrices how to speak perfectly.
        )
        
        model = get_peft_model(model, lora_config)

        # Ensure dynamic memory management to prevent OOM (Out of Memory) crashes on free GPUs
        def formatting_prompts_func(example):
            output_texts = []
            for i in range(len(example['messages'])):
                try:
                    # Wraps the Groq questions/answers in Qwen's standard conversational formatting (<|im_start|>)
                    formatted_text = tokenizer.apply_chat_template(
                        example['messages'][i], 
                        tokenize=False, 
                        add_generation_prompt=False
                    )
                    output_texts.append(formatted_text)
                except Exception:
                    continue
            return output_texts

        logger.info("Initiating standard SFT Engine...")
        
        # Safely fallback to standard if TRL collator structure changed in recent versions
        if HAS_COMP_COLLATOR:
            response_template = "<|im_start|>assistant\n"
            collator = DataCollatorForCompletionOnlyLM(response_template, tokenizer=tokenizer)
        else:
            logger.warning("Falling back to standard Causal LM Data Collator.")
            collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

        training_args = TrainingArguments(
            output_dir=self.output_dir,
            per_device_train_batch_size=1,   # Reduced batch size to prevent OOM
            gradient_accumulation_steps=8, 
            learning_rate=1e-4, 
            max_steps=2000,                  
            fp16=True,                       # Fix for T4 Tensor Cores
            bf16=False,                      
            gradient_checkpointing=True,     # Required for local hardware
            logging_steps=10,
            save_strategy="steps",
            save_steps=500,
            report_to="none"
        )

        trainer = SFTTrainer(
            model=model,
            train_dataset=dataset,
            args=training_args,
            formatting_func=formatting_prompts_func,
            data_collator=collator,
            max_seq_length=2048              # Max context size for conversational Q&A
        )

        logger.info("🚀 Igniting the Supervised Fine-Tuning Engine! (Cost: $0.00)")
        trainer.train()
        
        logger.info(f"💾 Generation Complete! Final 'Bharat-LLM' saved to {self.output_dir}")
        trainer.model.save_pretrained(self.output_dir)
        tokenizer.save_pretrained(self.output_dir)
